---
title: "Study area characteristics for: Drought may initiate western spruce budworm outbreaks, but multi-year periods of increased moisture availability promote widespread defoliation"
author: "Sarah J. Hart, Olivia Santiago, Joshua D. Carrell, and Thomas T. Veblen"
email: "sarah.hart@colostate.edu"
date: '`r format(Sys.time(), "%B %d, %Y")`'
output: 
   officedown::rdocx_document:
     reference_docx: Template.docx
bibliography: references.bib
csl: "`r here::here('citationstyle.csl')`"
link-citations: true
urlcolor: blue
linkcolor: blue
citationcolor: blue
---

```{r setup,include=FALSE, results='hide'}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE,
	progress = FALSE,
	cache = FALSE,
	dpi = 300,
  fig.align = 'center'
)

set.seed(513)
options(repos = c(CRAN = "http://cran.rstudio.com"))
options(timeout=60*30) # timeout downloads that last longer than 30 minutes

### Import libraries
if (!require("remotes"))  install.packages("remotes")
if (!require("pacman")) install.packages("pacman")
pacman::p_load(
  here, # easy file structure
  rmarkdown, # 
  flextable, # tables
  officer, # word documents
  bookdown, # word documents
  tidyverse, # data manipulation
  ggplot2, # figures
  RColorBrewer, # color palettes
  patchwork, # combining figures
  sf, # spatial data
  terra, # raster data (new pkg)
  raster, # raster data (old pkg)
  ncdf4, #import ncdf files
  tmap, # easy plotting of maps
  tmaptools, # helper library for tmap
  grid, # useful for plotting inset map
  terrainr, # dem
  prism # prism data
) 

proj.proj <- 4629

# Set custom plotting theme
theme_new <- function(base_size = 9,base_family = "Helvetica"){
  theme_classic(base_size = base_size, base_family = base_family) %+replace%
    theme(
      axis.line.x = element_line(color="black", linewidth = 0.25),
      axis.line.y = element_line(color="black", linewidth = 0.25),
      axis.title = element_text(size = 9),
      axis.text = element_text(colour="black", size=8),
      legend.key=element_rect(colour=NA, fill =NA),
      panel.grid = element_blank(),   
      plot.background = element_rect(fill = NA, colour = NA),
      panel.border = element_rect(fill = NA, colour = NA),
      panel.background = element_rect(fill = "white", colour = "black"), 
      strip.background = element_rect(fill = "white"),
      strip.text = element_text(size = 9)
      
    )
}
theme_set(theme_new())

set_flextable_defaults(
  font.family="Times", 
  font.size=12,
  line_spacing=1,
  padding.bottom=1,
  padding.top=1,
  text.align='center')

# Set directory structure for project
dir.create(here("Data", "Spatial"), showWarnings = FALSE)
dir.create(here("Results"), showWarnings = FALSE)
dir.create(here("Results", "Figures"), showWarnings = FALSE)
```

# Overview

The following code generates the study area map and characterizes the climate using data from PRISM [@prismclimategroup2021].

# Generate study area map
```{r Import_TreeRingSiteData}
host.meta <- read.csv(here("Data", "TreeRing", "Processed", "Host", "host-metadata.csv")) # import host metadata
nonhost.meta <- read.csv(here("Data", "TreeRing", "Processed", "Nonhost", "nonhost-metadata.csv")) # import nonhost metadata

hostXnonhost <- read.csv(here("Results", "hostXnonhost-subset.csv")) # import data describing the nonhost sites matched to each host site

host.meta.sub <- host.meta %>% filter(SeriesCode %in% hostXnonhost$host) # select only host sites 
  
select.nonhost.sites <- hostXnonhost[,c('nonhost1', 'nonhost2','nonhost3')] %>% unlist() %>% unique()
nonhost.meta.sub <- nonhost.meta[nonhost.meta$SeriesCode %in% select.nonhost.sites, ]
  
nonhost.sites <- st_as_sf(x = nonhost.meta.sub,  coords = c("Lon", "Lat"), crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs") %>% st_transform(proj.proj)

host.sites.sub <- st_as_sf(x = host.meta.sub, coords = c("Lon", "Lat"), crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs") %>% st_transform(proj.proj)

host.sites <- st_as_sf(x = host.meta, coords = c("Lon", "Lat"), crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs") %>% st_transform(proj.proj)
```

```{r FigStudyArea, results=F}
if(!file.exists(here("Results", "Figures", "FigStudyArea.jpg"))){
  states <- st_read(here("Data", "Spatial", "States", "cb_2018_us_state_20m.shp")) %>% st_transform(proj.proj)

  #Denver
  denver <- st_read(here("Data", "Spatial", "Cities", "Colorado_City_Point_Locations.shp")) %>% filter(NAME=="DENVER") %>% st_transform(proj.proj)

  # Convert raster of Douglas fir occurrence to polygon
  
  if(!file.exists(here("Data", "Spatial", "ITSPM","f202.shp"))){
    df.rast <- rast(here("Data", "Spatial", "ITSPM","f202"))
    srm <- st_read(here("Data", "Spatial", "EcoRegions", "us_eco_l3", "us_eco_l3.shp"), quiet=T) %>% filter(US_L3NAME=="Southern Rockies") %>% st_transform(crs=st_crs(df.rast)) %>% vect()
    df.rast <- crop(df.rast, srm)
    df.rast[df.rast<1] <- NA # set pixels were at least 1 of 64 pixels has Douglas fir
    df.rast[df.rast>=1] <- 1

    df.poly <- as.polygons(df.rast, aggregate=TRUE, values=TRUE, na.rm=TRUE) 
 
    writeVector(df.poly, here("Data", "Spatial", "ITSPM","f202.shp"), overwrite=T)
  }

  douglasfir <- vect(here("Data", "Spatial", "ITSPM","f202.shp")) %>% project(nonhost.sites) %>% st_as_sf()
  
  x <- tmaptools::bb(nonhost.sites)
  x[1] <- -107; x[2] <- 38.1; x[3] <- -104; x[4] <- 41.25
  asp1 <- (x$ymax - x$ymin)/(x$xmax - x$xmin)
  sg <- bb_poly(nonhost.sites, projection = st_crs(nonhost.sites))

  
  studyarea <- tm_shape(douglasfir, bbox=x) +  tm_fill(col="#5ab4ac") + tm_shape(nonhost.sites) +tm_symbols(size=0.25, shape=21,col="darkgray", alpha=1) + tm_shape(host.sites.sub) +tm_symbols(size=0.25, shape=17, col="black") + tm_shape(denver) +tm_symbols(shape=8, size=0.5, col="black") + tm_text("NAME", just=c(-0.25,0), size=0.7, remove.overlap=T) +  tm_scale_bar(position = c(0.95,0.005), text.size=0.75, just="right", breaks=c(0,50), bg.color="white", bg.alpha = 0.8)+tm_compass(position=c("right", "top"), text.size=0.75, size=2, type="4star")+tm_graticules(lines=F)

  wus <- states %>% filter(STUSPS %in% c("WA", "OR", "CA", "ID", "NV", "AZ", "MT", "UT", "NM", "CO", "WY")) %>% st_transform(st_crs(douglasfir))
  xy <- st_bbox(wus)
  asp2 <- (xy$xmax - xy$xmin)/(xy$ymax - xy$ymin)
  
  insetmap = tm_shape(wus) + tm_fill(col="lightgrey") +
  tm_shape(wus) + tm_borders(lwd = 1, col="grey") +
  tm_shape(sg) + tm_borders(lw=2, col="black") +
  tm_layout(inner.margins = c(0.04,0.04,0.04,0.04), outer.margins=c(0,0,0,0))
  
  w <- 0.3
  h <- asp2 * w
  vp <- viewport(x=0.15, y=0.009, width = w, height=h, just=c("left", "bottom"))
  
  tmap_save(studyarea,filename=here("Results", "Figures", "FigStudyArea.jpg"),
          dpi=300, insets_tm=insetmap, insets_vp=vp,
          height=4.5, width=3.5, units="in")
}
```

# Characterize climate
```{r CharacterizeClimate}
if(!file.exists(here("Results", "climate-norms-studyarea.csv"))){

  df.poly <-vect(here("Data", "Spatial", "ITSPM","f202.shp"))
  host.sites <- st_as_sf(x = host.meta, coords = c("Lon", "Lat"), crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs") %>% st_transform(st_crs(df.poly)) %>% st_buffer(1000)
  df.poly <- crop(df.poly, host.sites)
  
  prism_set_dl_dir(here("Data", "Spatial", "PRISM"))
  
  ppt.normal <- prism_archive_subset("ppt", "annual normals", resolution="800m") %>% pd_to_file() %>% rast()
  tmin1.normal <- prism_archive_subset("tmin", "monthly normals", mon=1, resolution="800m") %>% pd_to_file() %>% rast()
  tmax7.normal <- prism_archive_subset("tmax", "monthly normals", mon=7, resolution="800m") %>% pd_to_file() %>% rast()
  
  AET <- rast(here('Data', 'Spatial', 'Rodman', 'AET and CWD', 'AET_1981-2010.tif'))
  CWD <- rast(here('Data', 'Spatial', 'Rodman', 'AET and CWD', 'CWD_1981-2010.tif'))

  dem <- rast(here("Data", "Spatial", "DEM", "DEM250.tif"))
  
  df.poly <- df.poly %>% project(ppt.normal)
  climate.normals <- data.frame(metric=c("mean", "min", "max"))
  
  climate.normals$PPT <- NA
  climate.normals[climate.normals$metric=="mean", ]$PPT <- terra::zonal(z=df.poly, x=ppt.normal, fun=mean)[1,1]
  climate.normals[climate.normals$metric=="min", ]$PPT <- quantile(terra::extract(y=df.poly, x=tmin1.normal)[,2], 0.1)
  climate.normals[climate.normals$metric=="max", ]$PPT <- quantile(terra::extract(y=df.poly, x=tmin1.normal)[,2], 0.9)
  
  climate.normals$TMIN <- NA
  climate.normals[climate.normals$metric=="mean", ]$TMIN <- terra::zonal(z=df.poly, x=tmin1.normal, fun=mean)[1,1]
  climate.normals[climate.normals$metric=="min", ]$TMIN <-  quantile(terra::extract(y=df.poly, x=tmin1.normal)[,2], 0.1)
  climate.normals[climate.normals$metric=="max", ]$TMIN <- quantile(terra::extract(y=df.poly, x=tmin1.normal)[,2], 0.9)
  
  climate.normals$TMAX <- NA
  climate.normals[climate.normals$metric=="mean", ]$TMAX <- terra::zonal(z=df.poly, x=tmax7.normal, fun=mean)[1,1]
  climate.normals[climate.normals$metric=="min", ]$TMAX <-  quantile(terra::extract(y=df.poly, x=tmax7.normal)[,2], 0.1)
  climate.normals[climate.normals$metric=="max", ]$TMAX <- quantile(terra::extract(y=df.poly, x=tmax7.normal)[,2], 0.9)
  
   df.poly <- df.poly %>% project(AET)
   climate.normals$AET <- NA
   climate.normals[climate.normals$metric=="mean", ]$AET <- terra::zonal(z=df.poly, x=AET, fun=mean)[1,1]
   climate.normals[climate.normals$metric=="min", ]$AET <-  quantile(terra::extract(y=df.poly, x=AET)$`AET_1981-2010`, 0.1)
   climate.normals[climate.normals$metric=="max", ]$AET <- quantile(terra::extract(y=df.poly, x=AET)$`AET_1981-2010`, 0.9)

   df.poly <- df.poly %>% project(CWD)
   climate.normals$CWD <- NA
   climate.normals[climate.normals$metric=="mean", ]$CWD <- terra::zonal(z=df.poly, x=CWD, fun=mean)[1,1]
   climate.normals[climate.normals$metric=="min", ]$CWD <-  quantile(terra::extract(y=df.poly, x=CWD)$`CWD_1981-2010`, 0.1)
   climate.normals[climate.normals$metric=="max", ]$CWD <- quantile(terra::extract(y=df.poly, x=CWD)$`CWD_1981-2010`, 0.9)

   
   
  df.poly <- df.poly %>% project(dem)
  climate.normals$Elev <- NA
  climate.normals[climate.normals$metric=="mean", ]$Elev <- terra::zonal(z=df.poly, x=dem, fun=mean)[1,1]
  climate.normals[climate.normals$metric=="min", ]$Elev <-  quantile(terra::extract(y=df.poly, x=dem)$DEM250_3DEPElevation_1_1, 0.1)
  climate.normals[climate.normals$metric=="max", ]$Elev <- quantile(terra::extract(y=df.poly, x=dem)$DEM250_3DEPElevation_1_1, 0.9)

  write.csv(climate.normals, file=here("Results", "climate-norms-studyarea.csv"), row.names = F)
}
```

# References
